# Generated by Django 4.1 on 2023-06-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(blank=True, max_length=32, null=True)),
                ('since', models.DateTimeField()),
                ('uniform', models.CharField(blank=True, max_length=32, null=True)),
                ('level', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': '팀 정보',
                'verbose_name_plural': '팀 정보',
                'db_table': 'team',
            },
        ),
    ]
